"use client";

import { useState } from "react";
import { Activity, AlertTriangle, Building2, ChevronRight, ClipboardCheck, RefreshCw, ShieldAlert, ShieldCheck, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";

type Props={select:(row:string[])=>void;act:(message:string)=>void};
const events=[["EVT-88421","Kelvin Freeman","Clocked in · 8:03 AM","Monrovia HQ","Personal iPhone","Synced"],["EVT-88420","Hawa Sirleaf","Clocked in · 7:58 AM","Congo Town","Personal Android","Synced"],["EVT-88418","Samuel Toe","Clocked in · 8:24 AM","Monrovia HQ","Personal Android","Review"],["EVT-88402","Martha Kallon","Clocked out · Yesterday 5:06 PM","Monrovia HQ","Personal iPhone","Synced"],["EVT-88397","Rebecca Johnson","Leave request · 3 days","Mercy Hospital","Personal Android","Pending"]];

function State({value}:{value:string}){const tone=/synced|live|approved/i.test(value)?"green":/review|pending|returned/i.test(value)?"amber":"red";return <i className={`work-state ${tone}`}>{value}</i>}
function Metric({label,value,note,icon:Icon,tone="blue"}:{label:string;value:string;note:string;icon:any;tone?:string}){return <article className="work-metric"><span className={tone}><Icon/></span><div><small>{label}</small><b>{value}</b><em>{note}</em></div></article>}
function Box({title,action,children}:{title:string;action?:React.ReactNode;children:React.ReactNode}){return <section className="work-box"><header><h2>{title}</h2>{action}</header>{children}</section>}

export function WorkforceSync({select,act}:Props){
 const [live,setLive]=useState(true),[filter,setFilter]=useState("all");
 const [leave,setLeave]=useState([["LEV-2041","Hawa Sirleaf","Monrovia Business Group","Annual leave · Sep 14–18","Supervisor review"],["LEV-2042","Kelvin Freeman","Monrovia Business Group","Sick leave · Sep 8–10","HR evidence review"],["LEV-2050","Moses Kpannah","Divine University","Personal leave · Sep 11","Approved"]]);
 const visible=filter==="all"?events:events.filter(row=>row[5].toLowerCase()===filter);
 const decide=(id:string,status:string)=>{setLeave(rows=>rows.map(row=>row[0]===id?[...row.slice(0,4),status]:row));act(`${id} updated to ${status}; employer and employee views synchronized.`)};
 return <>
  <div className="sync-command"><div className="sync-source"><span><RefreshCw/></span><div><small>WORKFORCE SOURCE OF TRUTH</small><h2>Employee Personal accounts → Employer Portal</h2><p>Employees clock in, clock out and request leave in Prospeva Mobile. Verified events synchronize automatically for supervisor review and payroll approval.</p></div></div><div className="sync-switch"><span><b>Automatic synchronization</b><small>{live?"Connected employers are receiving events":"Synchronization paused"}</small></span><Switch checked={live} onCheckedChange={value=>{setLive(value);act(value?"Workforce synchronization resumed.":"Pause request recorded for operational approval.")}}/></div></div>
  <div className="work-metrics"><Metric label="Connected employees" value="48,620" note="Across 386 payroll employers" icon={Users}/><Metric label="Events synchronized today" value="91,284" note="99.94% delivered" icon={RefreshCw} tone="green"/><Metric label="Awaiting supervisor approval" value="136" note="Attendance and leave" icon={ClipboardCheck} tone="amber"/><Metric label="Sync exceptions" value="9" note="3 may affect payroll" icon={AlertTriangle} tone="red"/></div>
  <div className="sync-flow">{[["1","Employee Personal account","Clock in/out or request leave"],["2","Verification","Identity, device, location and timestamp"],["3","Employer Portal","Supervisor and HR review"],["4","Payroll lock","Only approved records affect pay"]].map((row,index)=><div key={row[0]}><i>{row[0]}</i><span><b>{row[1]}</b><small>{row[2]}</small></span>{index<3&&<ChevronRight/>}</div>)}</div>
  <div className="work-grid"><Box title="Live Personal-account events" action={<div className="sync-actions"><Select value={filter} onValueChange={setFilter}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All events</SelectItem><SelectItem value="synced">Synced</SelectItem><SelectItem value="review">Review</SelectItem><SelectItem value="pending">Pending</SelectItem></SelectContent></Select><Button variant="outline" onClick={()=>act("All workforce connections refreshed just now.")}><RefreshCw/>Sync now</Button></div>}><div className="event-feed">{visible.map(row=><button key={row[0]} onClick={()=>select(row)}><span className="work-avatar">{row[1].split(" ").map(name=>name[0]).join("")}</span><div><b>{row[1]}</b><small>{row[2]} · {row[3]}</small><em>{row[4]} · {row[0]}</em></div><State value={row[5]}/><ChevronRight/></button>)}</div></Box><Box title="Employer connection health"><div className="connection-list">{[["Monrovia Business Group","248 of 248 linked","Live"],["Divine University","889 of 892 linked","Review"],["Mercy Hospital","406 of 406 linked","Live"],["Hope Community School","124 of 126 linked","Review"]].map(row=><button key={row[0]} onClick={()=>select(row)}><Building2/><span><b>{row[0]}</b><small>{row[1]} Personal accounts</small></span><State value={row[2]}/></button>)}</div><div className="connection-note"><ShieldCheck/><span><b>No routine attendance input</b><small>The Employer Portal approves synchronized employee records. It does not create clock events for employees.</small></span></div></Box></div>
  <div className="work-grid lower"><Box title="Leave requests across employers"><div className="leave-control-table">{leave.map(row=><div key={row[0]}><span className="leave-icon"><ClipboardCheck/></span><span><b>{row[1]}</b><small>{row[2]} · {row[3]}</small></span><State value={row[4]}/><div>{row[4]!=="Approved"&&<><Button variant="outline" onClick={()=>decide(row[0],"Returned")}>Return</Button><Button onClick={()=>decide(row[0],"Approved")}>Approve</Button></>}</div></div>)}</div></Box><Box title="Controlled corrections"><div className="correction-policy"><ShieldAlert/><div><b>Corrections never overwrite original events</b><p>An authorized supervisor may propose a correction only with a reason, evidence and employee-visible audit history. HR approval is required before payroll changes.</p></div></div><div className="work-controls"><button onClick={()=>act("Nine sync exceptions opened.")}>Review failed or duplicate events <ChevronRight/></button><button onClick={()=>act("Correction approval queue opened.")}>Approve correction requests <ChevronRight/></button><button onClick={()=>act("Workforce synchronization audit exported.")}>Download synchronization audit <ChevronRight/></button></div></Box></div>
 </>;
}
